name: Auto Merge PR

# Controls when the action will run.
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["checkDQ"]
    types: [completed]
    branches:
      - 'data_set_for_life'
      - 'data_lotto_tb'
      - 'data_em_tb'

jobs:
  checkDQ:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Merge Pull Request 
        run: gh pr merge --merge "1"
        env:
          GH_TOKEN: ${{ secrets.FG_PAT }}